### ISSUE TITLE
error "Cannot copy non-existing folder" while creating inherited theme

### ISSUE THREAD

**Issue by jordajp** [getgrav/grav-plugin-devtools#33] opened 2018-08-04 14:56 UTC
https://github.com/getgrav/grav-plugin-devtools/blob/81ffcab0d9921c4b890d48d78b10ca3b97834e6a/cli/NewThemeCommand.php#L128

pb inherit**a**nce vs inherit**e**nce: 
According to my dictionary "inheritance" is correct. so I guess the directory `components/theme/inheritence/` should be `components/theme/inheritance/` instead. At least that how I manage to make it works.

**Comment by rhukster** [comment] 2018-08-04 17:16
Duplicate of #32

**Closed by rhukster** 2018-08-04 17:16 UTC
Labels: duplicate
